"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

fib = [1, 2]
i = 2
for number in range(4000000):
    if number == fib[i - 1] + fib[i - 2]:
        fib.append(number)
        i += 1

fib_2 = []
for number in fib:
    if number % 2 == 0:
        fib_2.append(number)
print(sum(fib_2))




